steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-productpage-v1:$TAG_NAME', '.']
  dir: 'src/productpage'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-details-v1:$TAG_NAME', '--build-arg', 'service_version=v1', '.']
  dir: 'src/details'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-details-v1:$TAG_NAME', '--build-arg', 'service_version=v2', '.']
  dir: 'src/details'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-ratings-v1:$TAG_NAME', '--build-arg', 'service_version=v1', '.']
  dir: 'src/ratings'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-ratings-v2:$TAG_NAME', '--build-arg', 'service_version=v2', '.']
  dir: 'src/ratings'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-reviews-v1:$TAG_NAME', '--build-arg', 'service_version=v1','.']
  dir: 'src/reviews'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-reviews-v2:$TAG_NAME', '--build-arg', 'service_version=v2','.']
  dir: 'src/reviews'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/examples-bookinfo-reviews-v3:$TAG_NAME', '--build-arg', 'service_version=v3','.']
  dir: 'src/reviews'
images: ['gcr.io/$PROJECT_ID/examples-bookinfo-productpage-v1:$TAG_NAME', 'gcr.io/$PROJECT_ID/examples-bookinfo-details-v1:$TAG_NAME', 'gcr.io/$PROJECT_ID/examples-bookinfo-details-v1:$TAG_NAME', 'gcr.io/$PROJECT_ID/examples-bookinfo-ratings-v1:$TAG_NAME', 'gcr.io/$PROJECT_ID/examples-bookinfo-ratings-v2:$TAG_NAME', 'gcr.io/$PROJECT_ID/examples-bookinfo-reviews-v1:$TAG_NAME', 'gcr.io/$PROJECT_ID/examples-bookinfo-reviews-v2:$TAG_NAME', 'gcr.io/$PROJECT_ID/examples-bookinfo-reviews-v3:$TAG_NAME']
